### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by suprafun** [Maumagnaguagno/HyperTensioN_U#15]
Hello, under what license is this project released under ? Thank-you.

**Comment by Maumagnaguagno** [comment]
We currently have [no license](https://choosealicense.com/no-permission/).
Why do you ask?

**Comment by suprafun** [comment]
I would to study it to learn more about HTN planning :)

**Comment by Maumagnaguagno** [comment]
I opted for **no license** to avoid multiple incompatible versions from forks, as I may break compatibility with previous versions during my research.

If you are learning HTN planning I would recommend [HyperTensioN](https://github.com/Maumagnaguagno/HyperTensioN), a simpler HTN which is extended by HyperTensioN_U to handle more complex descriptions.

You can download to use in your local machine for learning purposes.
