### ISSUE TITLE
Unfussyfy enforcement of file extensions

### ISSUE THREAD

**Issue by meneguzzi** [Maumagnaguagno/HyperTensioN_U#2]
May I suggest you comment out lines 30,34 and 35 of Hype.rb so that it accepts files named .jshop too? It's a bit pointless to just check for filenames.

**Comment by Maumagnaguagno** [comment]
Hype uses file extensions to select which parser to use.
If in the future we decide to support more types a massive renaming task would be required.
I will deactivate the file extension enforcement until a second parser exists.
File extensions still need to match, `domain.cookie / problem.cookie`, to avoid command line autocomplete errors.

**Comment by meneguzzi** [comment]
Got it, but, if you may let me suggest this, I'd use the filename as an optional way of detecting the parser, and allow for a command line parameter to force a certain parser (this applies to your other planner as well). The key thing is, most of the names we are enforcing are not standards, especially in the HTN planning community, so we'd have to do a massive renaming anyway whenever we take domains from other people.

**Comment by Maumagnaguagno** [comment]
Your idea of optional parser enforcement is interesting.
PDDL files usually comply with the file extension while SHOP and JSHOP files lack file extension or use `.txt`, so it was not a problem until now.
And if different extensions required the same parser (SHOP/JSHOP) it would be easy to make them all select the same module.
I never had to execute a batch of domains/problems from other planners were this was the main concern, usually the lack of features is the limiting factor.
