### ISSUE TITLE
Add probabilities to Healthcare domain

### ISSUE THREAD

**Issue by Maumagnaguagno** [Maumagnaguagno/HyperTensioN_U#9]
Healthcare domain is currently deterministic and does not consider rewards and costs.

**Comment by Maumagnaguagno** [comment]
Should the ``perform*`` or ``request*`` operators be modified to include probabilities?

**Perform:**
- ``(!performImaging ?radiologist ?patient ?physician)``
- ``(!performBiopsy ?radiologist ?patient ?physician)``

**Request:**
- ``(!requestAssessment ?patient ?physician)``
- ``(!requestImaging ?physician ?patient ?radiologist)``
- ``(!requestBiopsy ?physician ?patient ?pathologist)``
- ``(!requestPathologyReport ?physician ?radiologist ?patient)``
- ``(!requestRadiologyReport ?physician ?radiologist ?patient)``
- ``(!requestPhysicianReportAssessment ?patient ?physician ?hospital)``
- ``(!requestRadiologyReportAssessment ?pathologist ?radiologist ?patient ?hospital)``
- ``(!requestPathologyReportAssessment ?radiologist ?pathologist ?patient ?hospital)``

**Comment by meneguzzi** [comment]
The ```perform*``` operators should be modified to include probabilities.
